version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - XPACK_SECURITY_ENABLED=true
      - ELASTIC_USERNAME=your_es_user # replace with your user name
      - ELASTIC_PASSWORD=your_es_pwd  # replace with your password
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.16.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
      - XPACK_SECURITY_ENABLED=true
      - ELASTIC_USERNAME=your_es_user # replace with your user name
      - ELASTIC_PASSWORD=your_es_pwd  # replace with your password
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge